### PR TITLE
spyder 5.2.2

### PR DESCRIPTION
**Pull request by skupr-anaconda**
Requirements: https://github.com/spyder-ide/spyder/blob/v5.2.2/setup.py

Actions:
Update dependencies

### CODE REVIEW

**Comment by skupr-anaconda** [comment]
`Unsatisfiable dependencies for platform linux-64: {"jellyfish[version='>=0.7']", "python-lsp-server[version='>=1.3.2,<1.4.0']"}`

We have to add `jellyfish 0.9.0` and update p`ython-lsp-server to >=1.3.2,<1.4.0` (not the latest 1.4.0!)

**Comment by skupr-anaconda** [comment]
Only `spyder 5.3.0` supports `python 3.10` https://github.com/spyder-ide/spyder/issues/17562#issuecomment-1080806251

**Comment by skupr-anaconda** [comment]
spyder 5.3.0 https://github.com/AnacondaRecipes/spyder-feedstock/pull/9

**Comment by pseudoyim** [comment]
Handled in https://github.com/AnacondaRecipes/spyder-feedstock/pull/10

**Pull request closed without merging**
