### PR TITLE
spyder 5.3.3

### PR DESCRIPTION
**Pull request by skupr-anaconda**
Version change: bump from 5.2.2 to 5.3.3

Changelog: https://github.com/spyder-ide/spyder/blob/master/CHANGELOG.md
License: https://github.com/spyder-ide/spyder/blob/master/LICENSE.txt
Bug tracker: Lot of issues https://github.com/spyder-ide/spyder/issues
Requirements: https://github.com/spyder-ide/spyder/blob/v5.3.3/setup.py

Actions:
1. Remove `osx-zmq.patch` (**it should be discussed**)
2. Reset build number
3. Update pinnings for `run` dependencies: 
```
    - applaunchservices >=0.3.0
    - ipython >=7.31.1,<8.0.0
    - pylint >=2.5.0,<3.0
    - python-lsp-black >=1.2.0
    - pyqt >=5.6,<5.16
    - pyqtwebengine <5.16
    - python-lsp-server >=1.5.0,<1.6.0
    - pyzmq >=22.1.0
    - qdarkstyle >=3.0.2,<3.1.0
    - qtconsole >=5.3.2,<5.4.0
    - qtpy >=2.1.0
    - spyder-kernels >=2.3.3,<2.4.0
```
 4. Fix `pip check`
 5. Add `license_url `
 6. Add `doc_source_url`

### CODE REVIEW

**Comment by skupr-anaconda** [comment]
It's not clear why `pip check` fails for not installed `pyqt` and `pyqtwebengine` if they are already in the test environment:

```
spyder 5.3.3 requires pyqt5, which is not installed.

spyder 5.3.3 requires pyqtwebengine, which is not installed.

spyder-kernels 2.3.3 has requirement ipykernel<7,>=6.9.2; python_version >= "3", but you have ipykernel 6.9.1.

flake8 4.0.1 has requirement mccabe<0.7.0,>=0.6.0, but you have mccabe 0.7.0.
```

`flake8` warning can be ignored.
`spyder-kernels` should be updated to **2.3.3**

**Comment by skupr-anaconda** [comment]
`spyder-kernels 2.3.3` is available on defaults

**Review by katietz — APPROVED** [review]
lgtm, maybe a comment in front of - pyqtwebengine <5.16 to descirbe why we limit it here

**Review by pseudoyim — APPROVED** [review]
LGTM 👍 Thank you!

**Review by varlackc — APPROVED** [review]
LGTM

**Comment by skupr-anaconda** [comment]
> https://github.com/spyder-ide/spyder/blob/v5.3.3/setup.py

@katietz I've added comments about `pyqt` and `pyqtwebengine`:
```
    # Make Spyder work with PyQt 5.15, see https://github.com/spyder-ide/spyder/commit/a68e8b933b551581ed8d7504fe9430de66782927
    - pyqt >=5.6,<5.16
    # pyqtwebengine versions are available starting from 5.15+ 
    - pyqtwebengine >=5.15,<5.16
```

**Comment by skupr-anaconda** [comment]
Waiting for when the QA team will test the package as a GUI app.

**Pull request merged**
